### ISSUE TITLE
JWT with aud field cannot be verified

### ISSUE THREAD

**Issue by simonas-notcat** [uport-project/mouro#26]
It is not possible to send VP (which requires `aud` field) through `mouro`.
`verifyJWT` from `did-jwt` is checking if `aud` field in `JWT` is the same as the one passed in as a param. The fix could be in `did-jwt` or in mouro:

```ts
const decoded = decodeJWT(jwt)
const audience = decoded.payload.aud 
const verified = await verifyJWT(jwt, {resolver, audience})
```

**Comment by ajunge** [comment]
@simonas-notcat can you provide a sample VP (with the `aud` field) to test it?

**Comment by simonas-notcat** [comment]
`eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NkstUiJ9.eyJpYXQiOjE1NzM2NTMxNTcsImF1ZCI6ImRpZDpldGhyOjB4NDY0OTcyNWQ5NjE4MGJhODQ0MTVjNDdmMTNlZDUxYWMxOTRhODQxNSIsInZwIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIl0sInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiXSwidmVyaWZpYWJsZUNyZWRlbnRpYWwiOlsiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKRlV6STFOa3N0VWlKOS5leUpwWVhRaU9qRTFOek0yTlRNeE5UY3NJbk4xWWlJNkltUnBaRHBsZEdoeU9qQjRORFkwT1RjeU5XUTVOakU0TUdKaE9EUTBNVFZqTkRkbU1UTmxaRFV4WVdNeE9UUmhPRFF4TlNJc0luWmpJanA3SWtCamIyNTBaWGgwSWpwYkltaDBkSEJ6T2k4dmQzZDNMbmN6TG05eVp5OHlNREU0TDJOeVpXUmxiblJwWVd4ekwzWXhJbDBzSW5SNWNHVWlPbHNpVm1WeWFXWnBZV0pzWlVOeVpXUmxiblJwWVd3aVhTd2lZM0psWkdWdWRHbGhiRk4xWW1wbFkzUWlPbnNpWm1seWMzUk9ZVzFsSWpvaVZtVnliR0VpZlgwc0ltbHpjeUk2SW1ScFpEcGxkR2h5T2pCNE9XWmtaV1UzTWpJMk9UQmpZelZrWTJSak9XWmtOekEzTlRFek1tTTBPVFEwTWpKalpqVTBNaUo5LkRaWmZwYkZQWjRUWnhMWlZnU3J2OEp1bGotYlNzQ0Z6cmw3Zy10ZUQzd3ROSTZmQWktUHRrOVpRNGs3QkpKbG1LY1VBcG8ybDZlTEJaMGI4Yk1xMXFRQSIsImV5SjBlWEFpT2lKS1YxUWlMQ0poYkdjaU9pSkZVekkxTmtzdFVpSjkuZXlKcFlYUWlPakUxTnpNMk5UTXhOVGNzSW5OMVlpSTZJbVJwWkRwbGRHaHlPakI0TkRZME9UY3lOV1E1TmpFNE1HSmhPRFEwTVRWak5EZG1NVE5sWkRVeFlXTXhPVFJoT0RReE5TSXNJblpqSWpwN0lrQmpiMjUwWlhoMElqcGJJbWgwZEhCek9pOHZkM2QzTG5jekxtOXlaeTh5TURFNEwyTnlaV1JsYm5ScFlXeHpMM1l4SWwwc0luUjVjR1VpT2xzaVZtVnlhV1pwWVdKc1pVTnlaV1JsYm5ScFlXd2lYU3dpWTNKbFpHVnVkR2xoYkZOMVltcGxZM1FpT25zaWJHRnpkRTVoYldVaU9pSkhjbUZ1ZENKOWZTd2lhWE56SWpvaVpHbGtPbVYwYUhJNk1IZzVabVJsWlRjeU1qWTVNR05qTldSalpHTTVabVEzTURjMU1UTXlZelE1TkRReU1tTm1OVFF5SW4wLkRXaDRDVThiUWpUX1FaV01nNTlXcjN2R3pFbzU3WDFLMzdMOTV1TDFlV0NfaVJLMW51S2E2MkFyRVg2aEtIU1otcTZZUEIyVkZKcUNJT3NFQm5tbFBBQSJdfSwiaXNzIjoiZGlkOmV0aHI6MHg5ZmRlZTcyMjY5MGNjNWRjZGM5ZmQ3MDc1MTMyYzQ5NDQyMmNmNTQyIn0.xoT_r3Tiz_q6gGVNXQg04mpgxxueFqHfxThRx6NZ_AdJjqFETXQrJKOiHR3WyHPfZnRplCwVPzarT8sHhR_e7wE`
